# Generated by Django 4.1.5 on 2023-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders", name="oid", field=models.IntegerField(verbose_name=4),
        ),
    ]
